{% set data = load_setup_py_data() %}

package:
  name: figurepage
  version: {{ data.get('version') }}

source:
  git_url: "../"

build:
  noarch: python
  entry_points:
    - figurepage = figurepage:main

requirements:
  host:
    - python
  run:
    - python>=3.6.0

test:
  imports:
    - figurepage

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}
